// Mock data for development

export const mockGames = [
  {
    id: '1',
    title: 'Blackjack First Person',
    slug: 'blackjack-first-person',
    description: 'First person blackjack experience',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/blackjack-first-person',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 47,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Jeux populaires',
    category_slug: 'popular'
  },
  {
    id: '2',
    title: 'Baccarat',
    slug: 'baccarat',
    description: 'Classic baccarat game',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/baccarat',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 21,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Jeux populaires',
    category_slug: 'popular'
  },
  {
    id: '3',
    title: 'Blackjack',
    slug: 'blackjack',
    description: 'Classic blackjack',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/blackjack',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 63,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Jeux populaires',
    category_slug: 'popular'
  },
  {
    id: '4',
    title: 'Roulette',
    slug: 'roulette',
    description: 'European roulette',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/roulette',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 42,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Jeux populaires',
    category_slug: 'popular'
  },
  {
    id: '5',
    title: 'The Count',
    slug: 'the-count',
    description: 'Vampire-themed slot game',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/the-count',
    provider_name: 'Hacksaw Gaming',
    provider_slug: 'hacksaw',
    provider_logo: undefined,
    player_count: 85,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Jeux populaires',
    category_slug: 'popular'
  },
  {
    id: '6',
    title: 'Wild Bounty Showdown',
    slug: 'wild-bounty-showdown',
    description: 'Western-themed slot',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/wild-bounty',
    provider_name: 'PG',
    provider_slug: 'pg',
    provider_logo: undefined,
    player_count: 254,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Jeux populaires',
    category_slug: 'popular'
  },
  {
    id: '7',
    title: 'Spinman',
    slug: 'spinman',
    description: 'Superhero slot game',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/spinman',
    provider_name: 'Hacksaw Gaming',
    provider_slug: 'hacksaw',
    provider_logo: undefined,
    player_count: 48,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Jeux populaires',
    category_slug: 'popular'
  },
  {
    id: '8',
    title: 'Miami Mayhem',
    slug: 'miami-mayhem',
    description: 'Miami-themed slot',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/miami-mayhem',
    provider_name: 'Hacksaw Gaming',
    provider_slug: 'hacksaw',
    provider_logo: undefined,
    player_count: 46,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Jeux populaires',
    category_slug: 'popular'
  },
  {
    id: '9',
    title: 'Duck Hunters',
    slug: 'duck-hunters',
    description: 'Wild west duck hunting slot',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/duck-hunters',
    provider_name: 'Nolimit City',
    provider_slug: 'nolimit',
    provider_logo: undefined,
    player_count: 55,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Slots',
    category_slug: 'slots'
  },
  {
    id: '10',
    title: 'Clover Coins 3x3',
    slug: 'clover-coins-3x3',
    description: 'Lucky clover coin game',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/clover-coins-3x3',
    provider_name: 'TaDa Gaming',
    provider_slug: 'tada',
    provider_logo: undefined,
    player_count: 71,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Slots',
    category_slug: 'slots'
  },
  {
    id: '11',
    title: 'Clover Coins 4x4',
    slug: 'clover-coins-4x4',
    description: 'Lucky clover coin game 4x4',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/clover-coins-4x4',
    provider_name: 'TaDa Gaming',
    provider_slug: 'tada',
    provider_logo: undefined,
    player_count: 84,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Slots',
    category_slug: 'slots'
  },
  {
    id: '12',
    title: 'Temple of Torment',
    slug: 'temple-torment',
    description: 'Egyptian adventure slot',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/temple-torment',
    provider_name: 'Hacksaw Gaming',
    provider_slug: 'hacksaw',
    provider_logo: undefined,
    player_count: 70,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Slots',
    category_slug: 'slots'
  },
  {
    id: '13',
    title: 'Wild Bandito',
    slug: 'wild-bandito',
    description: 'Mariachi-themed slot',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/wild-bandito',
    provider_name: 'PG',
    provider_slug: 'pg',
    provider_logo: undefined,
    player_count: 44,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Slots',
    category_slug: 'slots'
  },
  {
    id: '14',
    title: 'Cocktail Nights',
    slug: 'cocktail-nights',
    description: 'Anime-style cocktail bar slot',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/cocktail-nights',
    provider_name: 'PG',
    provider_slug: 'pg',
    provider_logo: undefined,
    player_count: 55,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Slots',
    category_slug: 'slots'
  },
  {
    id: '15',
    title: 'Steamrunners',
    slug: 'steamrunners',
    description: 'Steampunk adventure slot',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/steamrunners',
    provider_name: 'Hacksaw Gaming',
    provider_slug: 'hacksaw',
    provider_logo: undefined,
    player_count: 53,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Slots',
    category_slug: 'slots'
  },
  {
    id: '16',
    title: 'Sweet Bonanza 1000',
    slug: 'sweet-bonanza-1000',
    description: 'Candy-themed slot',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/sweet-bonanza-1000',
    provider_name: 'Pragmatic Play',
    provider_slug: 'pragmatic-play',
    provider_logo: undefined,
    player_count: 28,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Slots',
    category_slug: 'slots'
  },
  {
    id: '17',
    title: 'Live Dealer 1',
    slug: 'live-dealer-1',
    description: 'Live casino dealer',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/live-dealer-1',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 120,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Casino en direct',
    category_slug: 'live-casino'
  },
  {
    id: '18',
    title: 'Live Dealer 2',
    slug: 'live-dealer-2',
    description: 'Live casino dealer',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/live-dealer-2',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 95,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Casino en direct',
    category_slug: 'live-casino'
  },
  {
    id: '19',
    title: 'Live Dealer 3',
    slug: 'live-dealer-3',
    description: 'Live casino dealer',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/live-dealer-3',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 78,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Casino en direct',
    category_slug: 'live-casino'
  },
  {
    id: '20',
    title: 'Live Dealer 4',
    slug: 'live-dealer-4',
    description: 'Live casino dealer',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/live-dealer-4',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 65,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Casino en direct',
    category_slug: 'live-casino'
  },
  {
    id: '21',
    title: 'Live Dealer 5',
    slug: 'live-dealer-5',
    description: 'Live casino dealer',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/live-dealer-5',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 88,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Casino en direct',
    category_slug: 'live-casino'
  },
  {
    id: '22',
    title: 'Live Dealer 6',
    slug: 'live-dealer-6',
    description: 'Live casino dealer',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/live-dealer-6',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 72,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Casino en direct',
    category_slug: 'live-casino'
  },
  {
    id: '23',
    title: 'Live Dealer 7',
    slug: 'live-dealer-7',
    description: 'Live casino dealer',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/live-dealer-7',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 91,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Casino en direct',
    category_slug: 'live-casino'
  },
  {
    id: '24',
    title: 'Live Dealer 8',
    slug: 'live-dealer-8',
    description: 'Live casino dealer',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/live-dealer-8',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 56,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Casino en direct',
    category_slug: 'live-casino'
  },
  {
    id: '25',
    title: 'BC Original Game',
    slug: 'bc-original',
    description: 'Exclusive boz.Topol original',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/bc-original',
    provider_name: 'boz.Topol',
    provider_slug: 'bc-game',
    provider_logo: undefined,
    player_count: 5678,
    multiplier: 5.0,
    is_new: false,
    is_exclusive: false,
    is_original: true,
    category_name: 'boz Originaux',
    category_slug: 'boz-originaux'
  },
  {
    id: '2',
    title: 'BC Original Game',
    slug: 'bc-original',
    description: 'Exclusive boz.Topol original',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/bc-original',
    provider_name: 'boz.Topol',
    provider_slug: 'bc-game',
    provider_logo: undefined,
    player_count: 5678,
    multiplier: 5.0,
    is_new: false,
    is_exclusive: false,
    is_original: true,
    category_name: 'boz Originaux',
    category_slug: 'boz-originaux'
  },
  {
    id: '3',
    title: 'Exclusive Roulette',
    slug: 'exclusive-roulette',
    description: 'Exclusive roulette game',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/roulette',
    provider_name: 'Evolution Gaming',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 890,
    multiplier: undefined,
    is_new: false,
    is_exclusive: true,
    is_original: false,
    category_name: 'Live Casino',
    category_slug: 'live-casino'
  },
  {
    id: '4',
    title: 'TV Game Show',
    slug: 'tv-game-show',
    description: 'Interactive TV game show',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/tv-show',
    provider_name: 'TV Games',
    provider_slug: 'tv-games',
    provider_logo: undefined,
    player_count: 2345,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Jeux télévisés',
    category_slug: 'tv-games'
  },
  {
    id: '5',
    title: 'Mega Fortune',
    slug: 'mega-fortune',
    description: 'Progressive jackpot slots',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/mega-fortune',
    provider_name: 'NetEnt',
    provider_slug: 'netent',
    provider_logo: undefined,
    player_count: 4567,
    multiplier: 10.0,
    is_new: true,
    is_exclusive: false,
    is_original: false,
    category_name: 'Slots',
    category_slug: 'slots'
  },
  {
    id: '6',
    title: 'Blackjack Pro',
    slug: 'blackjack-pro',
    description: 'Professional blackjack table',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/blackjack',
    provider_name: 'Evolution Gaming',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 678,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Table Games',
    category_slug: 'table-games'
  }
]

export const mockCategories = [
  { id: '1', name: 'Tous les jeux', slug: 'lobby', order: 0 },
  { id: '2', name: 'boz Originaux', slug: 'boz-originaux', order: 1 },
  { id: '3', name: 'BC Exclusif', slug: 'bc-exclusif', order: 2 },
  { id: '4', name: 'Jeux populaires', slug: 'popular', order: 3 },
  { id: '5', name: 'Machines à sous', slug: 'slots', order: 4 },
  { id: '6', name: 'Casino en direct', slug: 'live-casino', order: 5 },
  { id: '7', name: 'Jeux télévisés', slug: 'tv-games', order: 6 },
  { id: '8', name: 'Jeux de table', slug: 'table-games', order: 7 },
  { id: '9', name: 'Poker', slug: 'poker', order: 8 },
  { id: '10', name: 'Bingo', slug: 'bingo', order: 9 }
]

export const mockMatches = [
  {
    id: '1',
    sport_id: '1',
    league_id: '1',
    home_team: 'Paris Saint-Germain',
    away_team: 'Olympique de Marseille',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'live',
    match_time: '2024-01-15T20:00:00Z',
    current_score: '2-1',
    home_score: 2,
    away_score: 1,
    first_half_score: '1-0',
    second_half_score: '1-1',
    match_minute: 67,
    is_live: true,
    sport_name: 'Football',
    sport_slug: 'football',
    league_name: 'Ligue 1',
    league_slug: 'ligue-1',
    league_country: 'France'
  },
  {
    id: '2',
    sport_id: '1',
    league_id: '2',
    home_team: 'Real Madrid',
    away_team: 'Barcelona',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'upcoming',
    match_time: '2024-01-16T18:00:00Z',
    current_score: '0-0',
    home_score: 0,
    away_score: 0,
    first_half_score: undefined,
    second_half_score: undefined,
    match_minute: undefined,
    is_live: false,
    sport_name: 'Football',
    sport_slug: 'football',
    league_name: 'La Liga',
    league_slug: 'la-liga',
    league_country: 'Spain'
  },
  {
    id: '3',
    sport_id: '2',
    league_id: '3',
    home_team: 'Lakers',
    away_team: 'Warriors',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'live',
    match_time: '2024-01-15T22:00:00Z',
    current_score: '98-95',
    home_score: 98,
    away_score: 95,
    first_half_score: '48-45',
    second_half_score: '50-50',
    match_minute: 42,
    is_live: true,
    sport_name: 'Basketball',
    sport_slug: 'basketball',
    league_name: 'NBA',
    league_slug: 'nba',
    league_country: 'USA'
  },
  {
    id: '4',
    sport_id: '3',
    league_id: '4',
    home_team: 'Djokovic',
    away_team: 'Nadal',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'upcoming',
    match_time: '2024-01-17T14:00:00Z',
    current_score: '0-0',
    home_score: 0,
    away_score: 0,
    first_half_score: undefined,
    second_half_score: undefined,
    match_minute: undefined,
    is_live: false,
    sport_name: 'Tennis',
    sport_slug: 'tennis',
    league_name: 'ATP Masters',
    league_slug: 'atp-masters',
    league_country: 'International'
  },
  {
    id: '5',
    sport_id: '1',
    league_id: '5',
    home_team: 'Tottenham Hotspur FC',
    away_team: 'Liverpool FC',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'live',
    match_time: '2024-01-15T19:00:00Z',
    current_score: '1-2',
    home_score: 1,
    away_score: 2,
    first_half_score: '0-1',
    second_half_score: '1-1',
    match_minute: 98,
    is_live: true,
    sport_name: 'Football',
    sport_slug: 'football',
    league_name: 'Angleterre Premier League',
    league_slug: 'premier-league',
    league_country: 'England'
  },
  {
    id: '6',
    sport_id: '1',
    league_id: '6',
    home_team: 'RB Leipzig',
    away_team: 'Bayer Leverkusen',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'live',
    match_time: '2024-01-15T19:30:00Z',
    current_score: '1-3',
    home_score: 1,
    away_score: 3,
    first_half_score: '0-2',
    second_half_score: '1-1',
    match_minute: 101,
    is_live: true,
    sport_name: 'Football',
    sport_slug: 'football',
    league_name: 'Allemagne Bundesliga',
    league_slug: 'bundesliga',
    league_country: 'Germany'
  },
  {
    id: '7',
    sport_id: '1',
    league_id: '7',
    home_team: 'Excelsior Rotterdam',
    away_team: 'PEC Zwolle',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'live',
    match_time: '2024-01-15T20:00:00Z',
    current_score: '2-1',
    home_score: 2,
    away_score: 1,
    first_half_score: '1-0',
    second_half_score: '1-1',
    match_minute: 86,
    is_live: true,
    sport_name: 'Football',
    sport_slug: 'football',
    league_name: 'Pays-Bas Eredivisie',
    league_slug: 'eredivisie',
    league_country: 'Netherlands'
  },
  {
    id: '8',
    sport_id: '1',
    league_id: '7',
    home_team: 'NEC Nimègue',
    away_team: 'Ajax Amsterdam',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'live',
    match_time: '2024-01-15T20:15:00Z',
    current_score: '1-0',
    home_score: 1,
    away_score: 0,
    first_half_score: '1-0',
    second_half_score: '0-0',
    match_minute: 28,
    is_live: true,
    sport_name: 'Football',
    sport_slug: 'football',
    league_name: 'Pays-Bas Eredivisie',
    league_slug: 'eredivisie',
    league_country: 'Netherlands'
  },
  {
    id: '9',
    sport_id: '1',
    league_id: '8',
    home_team: 'Real Madrid',
    away_team: 'FC Séville',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'upcoming',
    match_time: 'Aujourd\'hui, 21:00',
    current_score: '0-0',
    home_score: 0,
    away_score: 0,
    first_half_score: undefined,
    second_half_score: undefined,
    match_minute: undefined,
    is_live: false,
    sport_name: 'Football',
    sport_slug: 'football',
    league_name: 'Espagne La Liga',
    league_slug: 'la-liga',
    league_country: 'Spain'
  },
  {
    id: '10',
    sport_id: '1',
    league_id: '9',
    home_team: 'Gil Vicente',
    away_team: 'Rio Ave',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'live',
    match_time: '2024-01-15T20:30:00Z',
    current_score: '2-2',
    home_score: 2,
    away_score: 2,
    first_half_score: '1-1',
    second_half_score: '1-1',
    match_minute: 72,
    is_live: true,
    sport_name: 'Football',
    sport_slug: 'football',
    league_name: 'Portugal Ligue 1 Portugaise',
    league_slug: 'liga-portugal',
    league_country: 'Portugal'
  },
  {
    id: '11',
    sport_id: '1',
    league_id: '10',
    home_team: 'Olympiakos',
    away_team: 'AE Kifisia FC',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'half-time',
    match_time: '2024-01-15T20:45:00Z',
    current_score: '1-1',
    home_score: 1,
    away_score: 1,
    first_half_score: '1-1',
    second_half_score: undefined,
    match_minute: 45,
    is_live: true,
    sport_name: 'Football',
    sport_slug: 'football',
    league_name: 'Grèce Super League',
    league_slug: 'super-league',
    league_country: 'Greece'
  }
]

export const mockMarkets = [
  {
    id: '1',
    name: 'Résultat du match',
    slug: 'match-result',
    type: '1X2',
    odds: [
      { id: '1', selection: '1', odds: 2.5, previousOdds: 2.4, change: 'up' },
      { id: '2', selection: 'X', odds: 3.2, previousOdds: 3.2, change: 'same' },
      { id: '3', selection: '2', odds: 2.8, previousOdds: 3.0, change: 'down' }
    ]
  },
  {
    id: '2',
    name: 'Double chance',
    slug: 'double-chance',
    type: 'double-chance',
    odds: [
      { id: '4', selection: '1X', odds: 1.5, previousOdds: 1.5, change: 'same' },
      { id: '5', selection: '12', odds: 1.3, previousOdds: 1.3, change: 'same' },
      { id: '6', selection: 'X2', odds: 1.6, previousOdds: 1.6, change: 'same' }
    ]
  },
  {
    id: '3',
    name: 'Total buts',
    slug: 'total-goals',
    type: 'over-under',
    odds: [
      { id: '7', selection: 'Over 2.5', odds: 1.8, previousOdds: 1.8, change: 'same' },
      { id: '8', selection: 'Under 2.5', odds: 2.0, previousOdds: 2.0, change: 'same' }
    ]
  }
]


export const mockGames = [
  {
    id: '1',
    title: 'Blackjack First Person',
    slug: 'blackjack-first-person',
    description: 'First person blackjack experience',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/blackjack-first-person',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 47,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Jeux populaires',
    category_slug: 'popular'
  },
  {
    id: '2',
    title: 'Baccarat',
    slug: 'baccarat',
    description: 'Classic baccarat game',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/baccarat',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 21,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Jeux populaires',
    category_slug: 'popular'
  },
  {
    id: '3',
    title: 'Blackjack',
    slug: 'blackjack',
    description: 'Classic blackjack',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/blackjack',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 63,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Jeux populaires',
    category_slug: 'popular'
  },
  {
    id: '4',
    title: 'Roulette',
    slug: 'roulette',
    description: 'European roulette',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/roulette',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 42,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Jeux populaires',
    category_slug: 'popular'
  },
  {
    id: '5',
    title: 'The Count',
    slug: 'the-count',
    description: 'Vampire-themed slot game',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/the-count',
    provider_name: 'Hacksaw Gaming',
    provider_slug: 'hacksaw',
    provider_logo: undefined,
    player_count: 85,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Jeux populaires',
    category_slug: 'popular'
  },
  {
    id: '6',
    title: 'Wild Bounty Showdown',
    slug: 'wild-bounty-showdown',
    description: 'Western-themed slot',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/wild-bounty',
    provider_name: 'PG',
    provider_slug: 'pg',
    provider_logo: undefined,
    player_count: 254,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Jeux populaires',
    category_slug: 'popular'
  },
  {
    id: '7',
    title: 'Spinman',
    slug: 'spinman',
    description: 'Superhero slot game',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/spinman',
    provider_name: 'Hacksaw Gaming',
    provider_slug: 'hacksaw',
    provider_logo: undefined,
    player_count: 48,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Jeux populaires',
    category_slug: 'popular'
  },
  {
    id: '8',
    title: 'Miami Mayhem',
    slug: 'miami-mayhem',
    description: 'Miami-themed slot',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/miami-mayhem',
    provider_name: 'Hacksaw Gaming',
    provider_slug: 'hacksaw',
    provider_logo: undefined,
    player_count: 46,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Jeux populaires',
    category_slug: 'popular'
  },
  {
    id: '9',
    title: 'Duck Hunters',
    slug: 'duck-hunters',
    description: 'Wild west duck hunting slot',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/duck-hunters',
    provider_name: 'Nolimit City',
    provider_slug: 'nolimit',
    provider_logo: undefined,
    player_count: 55,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Slots',
    category_slug: 'slots'
  },
  {
    id: '10',
    title: 'Clover Coins 3x3',
    slug: 'clover-coins-3x3',
    description: 'Lucky clover coin game',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/clover-coins-3x3',
    provider_name: 'TaDa Gaming',
    provider_slug: 'tada',
    provider_logo: undefined,
    player_count: 71,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Slots',
    category_slug: 'slots'
  },
  {
    id: '11',
    title: 'Clover Coins 4x4',
    slug: 'clover-coins-4x4',
    description: 'Lucky clover coin game 4x4',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/clover-coins-4x4',
    provider_name: 'TaDa Gaming',
    provider_slug: 'tada',
    provider_logo: undefined,
    player_count: 84,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Slots',
    category_slug: 'slots'
  },
  {
    id: '12',
    title: 'Temple of Torment',
    slug: 'temple-torment',
    description: 'Egyptian adventure slot',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/temple-torment',
    provider_name: 'Hacksaw Gaming',
    provider_slug: 'hacksaw',
    provider_logo: undefined,
    player_count: 70,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Slots',
    category_slug: 'slots'
  },
  {
    id: '13',
    title: 'Wild Bandito',
    slug: 'wild-bandito',
    description: 'Mariachi-themed slot',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/wild-bandito',
    provider_name: 'PG',
    provider_slug: 'pg',
    provider_logo: undefined,
    player_count: 44,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Slots',
    category_slug: 'slots'
  },
  {
    id: '14',
    title: 'Cocktail Nights',
    slug: 'cocktail-nights',
    description: 'Anime-style cocktail bar slot',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/cocktail-nights',
    provider_name: 'PG',
    provider_slug: 'pg',
    provider_logo: undefined,
    player_count: 55,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Slots',
    category_slug: 'slots'
  },
  {
    id: '15',
    title: 'Steamrunners',
    slug: 'steamrunners',
    description: 'Steampunk adventure slot',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/steamrunners',
    provider_name: 'Hacksaw Gaming',
    provider_slug: 'hacksaw',
    provider_logo: undefined,
    player_count: 53,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Slots',
    category_slug: 'slots'
  },
  {
    id: '16',
    title: 'Sweet Bonanza 1000',
    slug: 'sweet-bonanza-1000',
    description: 'Candy-themed slot',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/sweet-bonanza-1000',
    provider_name: 'Pragmatic Play',
    provider_slug: 'pragmatic-play',
    provider_logo: undefined,
    player_count: 28,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Slots',
    category_slug: 'slots'
  },
  {
    id: '17',
    title: 'Live Dealer 1',
    slug: 'live-dealer-1',
    description: 'Live casino dealer',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/live-dealer-1',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 120,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Casino en direct',
    category_slug: 'live-casino'
  },
  {
    id: '18',
    title: 'Live Dealer 2',
    slug: 'live-dealer-2',
    description: 'Live casino dealer',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/live-dealer-2',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 95,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Casino en direct',
    category_slug: 'live-casino'
  },
  {
    id: '19',
    title: 'Live Dealer 3',
    slug: 'live-dealer-3',
    description: 'Live casino dealer',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/live-dealer-3',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 78,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Casino en direct',
    category_slug: 'live-casino'
  },
  {
    id: '20',
    title: 'Live Dealer 4',
    slug: 'live-dealer-4',
    description: 'Live casino dealer',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/live-dealer-4',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 65,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Casino en direct',
    category_slug: 'live-casino'
  },
  {
    id: '21',
    title: 'Live Dealer 5',
    slug: 'live-dealer-5',
    description: 'Live casino dealer',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/live-dealer-5',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 88,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Casino en direct',
    category_slug: 'live-casino'
  },
  {
    id: '22',
    title: 'Live Dealer 6',
    slug: 'live-dealer-6',
    description: 'Live casino dealer',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/live-dealer-6',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 72,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Casino en direct',
    category_slug: 'live-casino'
  },
  {
    id: '23',
    title: 'Live Dealer 7',
    slug: 'live-dealer-7',
    description: 'Live casino dealer',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/live-dealer-7',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 91,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Casino en direct',
    category_slug: 'live-casino'
  },
  {
    id: '24',
    title: 'Live Dealer 8',
    slug: 'live-dealer-8',
    description: 'Live casino dealer',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/live-dealer-8',
    provider_name: 'Evolution',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 56,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Casino en direct',
    category_slug: 'live-casino'
  },
  {
    id: '25',
    title: 'BC Original Game',
    slug: 'bc-original',
    description: 'Exclusive boz.Topol original',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/bc-original',
    provider_name: 'boz.Topol',
    provider_slug: 'bc-game',
    provider_logo: undefined,
    player_count: 5678,
    multiplier: 5.0,
    is_new: false,
    is_exclusive: false,
    is_original: true,
    category_name: 'boz Originaux',
    category_slug: 'boz-originaux'
  },
  {
    id: '2',
    title: 'BC Original Game',
    slug: 'bc-original',
    description: 'Exclusive boz.Topol original',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/bc-original',
    provider_name: 'boz.Topol',
    provider_slug: 'bc-game',
    provider_logo: undefined,
    player_count: 5678,
    multiplier: 5.0,
    is_new: false,
    is_exclusive: false,
    is_original: true,
    category_name: 'boz Originaux',
    category_slug: 'boz-originaux'
  },
  {
    id: '3',
    title: 'Exclusive Roulette',
    slug: 'exclusive-roulette',
    description: 'Exclusive roulette game',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/roulette',
    provider_name: 'Evolution Gaming',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 890,
    multiplier: undefined,
    is_new: false,
    is_exclusive: true,
    is_original: false,
    category_name: 'Live Casino',
    category_slug: 'live-casino'
  },
  {
    id: '4',
    title: 'TV Game Show',
    slug: 'tv-game-show',
    description: 'Interactive TV game show',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/tv-show',
    provider_name: 'TV Games',
    provider_slug: 'tv-games',
    provider_logo: undefined,
    player_count: 2345,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Jeux télévisés',
    category_slug: 'tv-games'
  },
  {
    id: '5',
    title: 'Mega Fortune',
    slug: 'mega-fortune',
    description: 'Progressive jackpot slots',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/mega-fortune',
    provider_name: 'NetEnt',
    provider_slug: 'netent',
    provider_logo: undefined,
    player_count: 4567,
    multiplier: 10.0,
    is_new: true,
    is_exclusive: false,
    is_original: false,
    category_name: 'Slots',
    category_slug: 'slots'
  },
  {
    id: '6',
    title: 'Blackjack Pro',
    slug: 'blackjack-pro',
    description: 'Professional blackjack table',
    thumbnail_url: undefined,
    game_url: 'https://example.com/games/blackjack',
    provider_name: 'Evolution Gaming',
    provider_slug: 'evolution',
    provider_logo: undefined,
    player_count: 678,
    multiplier: undefined,
    is_new: false,
    is_exclusive: false,
    is_original: false,
    category_name: 'Table Games',
    category_slug: 'table-games'
  }
]

export const mockCategories = [
  { id: '1', name: 'Tous les jeux', slug: 'lobby', order: 0 },
  { id: '2', name: 'boz Originaux', slug: 'boz-originaux', order: 1 },
  { id: '3', name: 'BC Exclusif', slug: 'bc-exclusif', order: 2 },
  { id: '4', name: 'Jeux populaires', slug: 'popular', order: 3 },
  { id: '5', name: 'Machines à sous', slug: 'slots', order: 4 },
  { id: '6', name: 'Casino en direct', slug: 'live-casino', order: 5 },
  { id: '7', name: 'Jeux télévisés', slug: 'tv-games', order: 6 },
  { id: '8', name: 'Jeux de table', slug: 'table-games', order: 7 },
  { id: '9', name: 'Poker', slug: 'poker', order: 8 },
  { id: '10', name: 'Bingo', slug: 'bingo', order: 9 }
]

export const mockMatches = [
  {
    id: '1',
    sport_id: '1',
    league_id: '1',
    home_team: 'Paris Saint-Germain',
    away_team: 'Olympique de Marseille',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'live',
    match_time: '2024-01-15T20:00:00Z',
    current_score: '2-1',
    home_score: 2,
    away_score: 1,
    first_half_score: '1-0',
    second_half_score: '1-1',
    match_minute: 67,
    is_live: true,
    sport_name: 'Football',
    sport_slug: 'football',
    league_name: 'Ligue 1',
    league_slug: 'ligue-1',
    league_country: 'France'
  },
  {
    id: '2',
    sport_id: '1',
    league_id: '2',
    home_team: 'Real Madrid',
    away_team: 'Barcelona',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'upcoming',
    match_time: '2024-01-16T18:00:00Z',
    current_score: '0-0',
    home_score: 0,
    away_score: 0,
    first_half_score: undefined,
    second_half_score: undefined,
    match_minute: undefined,
    is_live: false,
    sport_name: 'Football',
    sport_slug: 'football',
    league_name: 'La Liga',
    league_slug: 'la-liga',
    league_country: 'Spain'
  },
  {
    id: '3',
    sport_id: '2',
    league_id: '3',
    home_team: 'Lakers',
    away_team: 'Warriors',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'live',
    match_time: '2024-01-15T22:00:00Z',
    current_score: '98-95',
    home_score: 98,
    away_score: 95,
    first_half_score: '48-45',
    second_half_score: '50-50',
    match_minute: 42,
    is_live: true,
    sport_name: 'Basketball',
    sport_slug: 'basketball',
    league_name: 'NBA',
    league_slug: 'nba',
    league_country: 'USA'
  },
  {
    id: '4',
    sport_id: '3',
    league_id: '4',
    home_team: 'Djokovic',
    away_team: 'Nadal',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'upcoming',
    match_time: '2024-01-17T14:00:00Z',
    current_score: '0-0',
    home_score: 0,
    away_score: 0,
    first_half_score: undefined,
    second_half_score: undefined,
    match_minute: undefined,
    is_live: false,
    sport_name: 'Tennis',
    sport_slug: 'tennis',
    league_name: 'ATP Masters',
    league_slug: 'atp-masters',
    league_country: 'International'
  },
  {
    id: '5',
    sport_id: '1',
    league_id: '5',
    home_team: 'Tottenham Hotspur FC',
    away_team: 'Liverpool FC',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'live',
    match_time: '2024-01-15T19:00:00Z',
    current_score: '1-2',
    home_score: 1,
    away_score: 2,
    first_half_score: '0-1',
    second_half_score: '1-1',
    match_minute: 98,
    is_live: true,
    sport_name: 'Football',
    sport_slug: 'football',
    league_name: 'Angleterre Premier League',
    league_slug: 'premier-league',
    league_country: 'England'
  },
  {
    id: '6',
    sport_id: '1',
    league_id: '6',
    home_team: 'RB Leipzig',
    away_team: 'Bayer Leverkusen',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'live',
    match_time: '2024-01-15T19:30:00Z',
    current_score: '1-3',
    home_score: 1,
    away_score: 3,
    first_half_score: '0-2',
    second_half_score: '1-1',
    match_minute: 101,
    is_live: true,
    sport_name: 'Football',
    sport_slug: 'football',
    league_name: 'Allemagne Bundesliga',
    league_slug: 'bundesliga',
    league_country: 'Germany'
  },
  {
    id: '7',
    sport_id: '1',
    league_id: '7',
    home_team: 'Excelsior Rotterdam',
    away_team: 'PEC Zwolle',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'live',
    match_time: '2024-01-15T20:00:00Z',
    current_score: '2-1',
    home_score: 2,
    away_score: 1,
    first_half_score: '1-0',
    second_half_score: '1-1',
    match_minute: 86,
    is_live: true,
    sport_name: 'Football',
    sport_slug: 'football',
    league_name: 'Pays-Bas Eredivisie',
    league_slug: 'eredivisie',
    league_country: 'Netherlands'
  },
  {
    id: '8',
    sport_id: '1',
    league_id: '7',
    home_team: 'NEC Nimègue',
    away_team: 'Ajax Amsterdam',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'live',
    match_time: '2024-01-15T20:15:00Z',
    current_score: '1-0',
    home_score: 1,
    away_score: 0,
    first_half_score: '1-0',
    second_half_score: '0-0',
    match_minute: 28,
    is_live: true,
    sport_name: 'Football',
    sport_slug: 'football',
    league_name: 'Pays-Bas Eredivisie',
    league_slug: 'eredivisie',
    league_country: 'Netherlands'
  },
  {
    id: '9',
    sport_id: '1',
    league_id: '8',
    home_team: 'Real Madrid',
    away_team: 'FC Séville',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'upcoming',
    match_time: 'Aujourd\'hui, 21:00',
    current_score: '0-0',
    home_score: 0,
    away_score: 0,
    first_half_score: undefined,
    second_half_score: undefined,
    match_minute: undefined,
    is_live: false,
    sport_name: 'Football',
    sport_slug: 'football',
    league_name: 'Espagne La Liga',
    league_slug: 'la-liga',
    league_country: 'Spain'
  },
  {
    id: '10',
    sport_id: '1',
    league_id: '9',
    home_team: 'Gil Vicente',
    away_team: 'Rio Ave',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'live',
    match_time: '2024-01-15T20:30:00Z',
    current_score: '2-2',
    home_score: 2,
    away_score: 2,
    first_half_score: '1-1',
    second_half_score: '1-1',
    match_minute: 72,
    is_live: true,
    sport_name: 'Football',
    sport_slug: 'football',
    league_name: 'Portugal Ligue 1 Portugaise',
    league_slug: 'liga-portugal',
    league_country: 'Portugal'
  },
  {
    id: '11',
    sport_id: '1',
    league_id: '10',
    home_team: 'Olympiakos',
    away_team: 'AE Kifisia FC',
    home_team_logo: undefined,
    away_team_logo: undefined,
    status: 'half-time',
    match_time: '2024-01-15T20:45:00Z',
    current_score: '1-1',
    home_score: 1,
    away_score: 1,
    first_half_score: '1-1',
    second_half_score: undefined,
    match_minute: 45,
    is_live: true,
    sport_name: 'Football',
    sport_slug: 'football',
    league_name: 'Grèce Super League',
    league_slug: 'super-league',
    league_country: 'Greece'
  }
]

export const mockMarkets = [
  {
    id: '1',
    name: 'Résultat du match',
    slug: 'match-result',
    type: '1X2',
    odds: [
      { id: '1', selection: '1', odds: 2.5, previousOdds: 2.4, change: 'up' },
      { id: '2', selection: 'X', odds: 3.2, previousOdds: 3.2, change: 'same' },
      { id: '3', selection: '2', odds: 2.8, previousOdds: 3.0, change: 'down' }
    ]
  },
  {
    id: '2',
    name: 'Double chance',
    slug: 'double-chance',
    type: 'double-chance',
    odds: [
      { id: '4', selection: '1X', odds: 1.5, previousOdds: 1.5, change: 'same' },
      { id: '5', selection: '12', odds: 1.3, previousOdds: 1.3, change: 'same' },
      { id: '6', selection: 'X2', odds: 1.6, previousOdds: 1.6, change: 'same' }
    ]
  },
  {
    id: '3',
    name: 'Total buts',
    slug: 'total-goals',
    type: 'over-under',
    odds: [
      { id: '7', selection: 'Over 2.5', odds: 1.8, previousOdds: 1.8, change: 'same' },
      { id: '8', selection: 'Under 2.5', odds: 2.0, previousOdds: 2.0, change: 'same' }
    ]
  }
]

